Julia Kozeeva Tasks 91-100
juliakozeeva/ui-internship-lwo2 pull request #10
Opened 2019-09-23 09:13 UTC by juliakozeeva

2019-09-24 11:35 UTC, alexkond requested changes

2019-09-24 11:35 UTC, alexkond commented on tasks/91_make-a-person/make-a-person.js
> +    this.fullname[0] = firstAndLast.split(' ')[0];
You could simplify it like this:
```javascript
this.fullname = firstAndLast.split(' ');
```

2019-09-24 11:35 UTC, alexkond commented on tasks/98_linked-list/linked-list.js
> +    let result = 0;
I think you can create a field like `length` and update it on `push` and `pop` and return it here instead of calculating it on every call.

2019-09-24 11:35 UTC, alexkond commented on tasks/99_stack/stack.js
> +    let last = this.last;
Same as with `LinkedList` `ammount` property.

2019-09-24 12:29 UTC, alexkond submitted a review, later dismissed

2019-09-25 08:00 UTC, savchukm requested changes

2019-09-25 08:00 UTC, savchukm commented on tasks/92_calculate-orbital-period/calculate-orbital-period.js
> +      delete arr[prop].avgAlt;
Mutating of original args is a bad practice. You should create new object

2019-09-25 08:00 UTC, savchukm commented on tasks/95_fat-fingers/fat-fingers.js
> +      reverse ? reverse = false : reverse = true;
`reverse = !reverse`

2019-09-25 09:17 UTC, savchukm submitted a review, later dismissed

2019-09-25 10:02 UTC, savchukm approved these changes

2019-09-25 10:21 UTC, vovcyan approved these changes

2019-09-25 10:29 UTC, merged