Julia Kozeeva Tasks 51-60
juliakozeeva/ui-internship-lwo2 pull request #6
Opened 2019-09-17 10:01 UTC by juliakozeeva

2019-09-17 17:14 UTC, vovcyan requested changes

2019-09-17 17:14 UTC, vovcyan commented on tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
> +
/**
 *
 */
function ...

You don't need to add a line btw

2019-09-17 17:15 UTC, vovcyan requested changes

2019-09-17 17:15 UTC, vovcyan commented on tasks/59_unite-unique/unite-unique.js
> +  return Array.from(new Set(totalArray));
Split it

2019-09-17 17:15 UTC, vovcyan commented on tasks/60_convert-html-entities/convert-html-entities.js
> +      let regex = new RegExp(key, 'g');
const

2019-09-18 07:29 UTC, vovcyan approved these changes

2019-09-19 05:25 UTC, savchukm approved these changes

2019-09-19 05:44 UTC, merged