Julia Kozeeva Tasks 61-70
juliakozeeva/ui-internship-lwo2 pull request #7
Opened 2019-09-18 10:50 UTC by juliakozeeva

2019-09-19 05:51 UTC, alexkond requested changes

2019-09-19 05:51 UTC, alexkond commented on tasks/69_unpack-elements/unpack-elements.js
> +  function flatten(arr) {
`flatten()` function could be declared in the outer scope

2019-09-20 07:08 UTC, KalachevDev approved these changes

2019-09-20 12:59 UTC, alexkond approved these changes

2019-09-20 13:00 UTC, merged