Julia Kozeeva Tasks 81-90
juliakozeeva/ui-internship-lwo2 pull request #9
Opened 2019-09-20 12:48 UTC by juliakozeeva

2019-09-24 11:16 UTC, alexkond requested changes

2019-09-24 11:16 UTC, alexkond commented on tasks/86_working-hours/working-hours.js
> +      workdaysSort[i] = workdays.find((d) => d.day === days[i]);
Consider using `sort()` method instead

2019-09-24 11:32 UTC, juliakozeeva commented on tasks/86_working-hours/working-hours.js
> +      workdaysSort[i] = workdays.find((d) => d.day === days[i]);
fixed it)

2019-09-24 11:36 UTC, alexkond approved these changes

2019-09-25 07:22 UTC, savchukm approved these changes

2019-09-25 07:27 UTC, merged